name: 'ga4_attribution'
version: '1.0.0'
config-version: 2

profile: 'ga4_attribution'   # must match profiles.yml top key

model-paths: ["models"]

models:
  ga4_attribution:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
