ga4_attribution:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: dbtproject-395506   # your GCP project id
      dataset: ga4_demo            # your schema for models
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
